name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install tools
        run: |
             python -m pip install --upgrade pip pytest
             pip install coverage 

      - name: Test with unittest
        working-directory: ./scripts
        run: python3 -m unittest chatbot_test.py

      - name: Check code coverage
        working-directory: ./scripts
        run: |
          python3 -m coverage run -m unittest chatbot_test.py
          python3 -m coverage report
          python3 -m coverage html
                
      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v4
        with:
            name: code-coverage-report
            path: htmlcov